# Numpy Assignment1 For Sir Qasim

In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
a = [1,2,3]
b = [4,5,6]
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [7]:
ar = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]],[[9,10],[11,12]]])
ar.size

12

In [8]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [9]:
l = np.arange(1000000)

In [10]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 7.58 s


In [11]:
%time for i in range(1,10): r=l*2

Wall time: 166 ms


In [12]:
m = np.random.randn((10))
print(m)

[ 1.20863897e-03 -2.77210471e-01 -4.74533631e-01 -2.09697427e-01
 -7.71343737e-01  1.54022532e+00  1.04735759e+00  1.43126446e+00
 -7.79815664e-01  4.35088146e-01]


In [13]:
n = np.random.randn((10))
print(n)

[ 0.45329398 -0.26558431  0.75271477  0.0347086  -1.8719056  -0.14203513
 -0.6660347   0.65030921 -1.23505657  0.34089651]


In [14]:
m+n

array([ 0.45450262, -0.54279478,  0.27818114, -0.17498883, -2.64324933,
        1.39819019,  0.3813229 ,  2.08157367, -2.01487223,  0.77598466])

In [15]:
m-n

array([-0.45208534, -0.01162616, -1.22724841, -0.24440602,  1.10056186,
        1.68226045,  1.71339229,  0.78095525,  0.45524091,  0.09419164])

In [16]:
m*2

array([ 2.41727793e-03, -5.54420941e-01, -9.49067262e-01, -4.19394854e-01,
       -1.54268747e+00,  3.08045065e+00,  2.09471519e+00,  2.86252892e+00,
       -1.55963133e+00,  8.70176292e-01])

In [17]:
1/n

array([ 2.20607386, -3.76528268,  1.32852447, 28.81130549, -0.53421497,
       -7.04051181, -1.50142328,  1.53773002, -0.80967951,  2.93344159])

In [18]:
m>0

array([ True, False, False, False, False,  True,  True,  True, False,
        True])

# # Indexing & Slicing of ndarray

In [19]:
l = np.arange(25).reshape(5,5)
l

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
l[1:3,3:]

array([[ 8,  9],
       [13, 14]])

In [21]:
l[4,3]

23

In [22]:
l[0,3],l[2,2],l[3,4],l[0,3]

(3, 12, 19, 3)

# # logical operations on ndarray

In [23]:
larr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(larr[larr > 5])

[ 6  7  8  9 10 11 12]


In [24]:
even = larr[larr%2==0]
print(even)

[ 2  4  6  8 10 12]


In [25]:
odd = larr[larr/2==0]
print(odd)

[]


In [26]:
logic = larr[(larr > 2) & (larr < 11)]
print(logic)

[ 3  4  5  6  7  8  9 10]


In [27]:
logic = larr[(larr>5) | (larr==7)]
print(logic)

[ 6  7  8  9 10 11 12]


In [28]:
k= np.arange(20).reshape(4,5)
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
k.sum()

190

In [30]:
k.min()

0

In [31]:
k.max()

19

# Changing specific elements , rows, columns

In [32]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
a.shape

(2, 7)

In [34]:
# getting a specific element (r,c)
a[1,5]

13

In [35]:
a[0, 1:6:2]

array([2, 4, 6])

In [36]:
# getting a specific coulmn
a[:,2]

array([ 3, 10])

In [38]:
print("Orignal Array : \n", a)
a[1,5] = 20
print("After Changing second row sixth element :\n", a )

Orignal Array : 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
After Changing second row sixth element :
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [40]:
# by using 3dArray
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
a[0,1,1]

5

# numpy.flatten() with 2D Array

In [43]:
a = np.array([[7,5], [2,6]])
a

array([[7, 5],
       [2, 6]])

In [44]:
a.flatten()

array([7, 5, 2, 6])

# numpy.flatten() with 3D Array

In [45]:
b = np.array([[5,6,4], [1,7,3], [2,9,8]])
b

array([[5, 6, 4],
       [1, 7, 3],
       [2, 9, 8]])

In [46]:
b.flatten()

array([5, 6, 4, 1, 7, 3, 2, 9, 8])

# numpy.ravel() with 2D Array

In [47]:
x = np.array([[4, 5],[7,6]])
x

array([[4, 5],
       [7, 6]])

In [48]:
np.ravel(x)

array([4, 5, 7, 6])

#  numpy.ravel() with 3D array

In [49]:
y = np.array([[5,8,2],[4,3,7],[6,9,1]])
y

array([[5, 8, 2],
       [4, 3, 7],
       [6, 9, 1]])

In [50]:
np.ravel(y)

array([5, 8, 2, 4, 3, 7, 6, 9, 1])